### ISSUE TITLE
StructureFromMotion does not result in point cloud

### ISSUE THREAD

**Issue by Baasje85** [natowi/mr_dev_build#3]
After the successful SfM step, no point cloud is presented in the 3D Viewer. While the camera's are reconstructed. Double click on the node also does not work.

![image](https://user-images.githubusercontent.com/51262792/61410980-a8886900-a8e5-11e9-8b08-7e1d9800550a.png)

**Comment by natowi** [comment]
I am aware of this problem, but I don´t know the cause. Maybe I missed something while compiling.

**Comment by natowi** [comment]
I see, I missed building qmlAlembic. You can copy paste the qtPlugins folder from the official Meshroom build folder to fix this.

**Comment by skinkie** [comment]
Confirmed that copying qtPlugins solves this issue.
